(library
 (name skyline_error_view_v1)
 (public_name skyline.error_view_v1)
 (preprocess
  (pps ppx_jane bonsai.ppx_bonsai))
 (libraries bonsai_web bonsai_web_components.bonsai_clipboard
   bonsai_web_components.codicons core skyline_banner_v1
   skyline_context_menu_v1 skyline_errors_v1 skyline_theme_v1))
