(library
 (name skyline_banner_v1)
 (public_name skyline.banner_v1)
 (preprocess
  (pps ppx_jane js_of_ocaml-ppx bonsai.ppx_bonsai ppx_css))
 (libraries bonsai bonsai_web bonsai_web_components.codicons core
   virtual_dom.css_gen skyline_button_v1 skyline_card_v1
   skyline_context_menu_v1 skyline_divider_v1 skyline_flex_v1
   skyline_loading_indicator_v1 skyline_popover_v1 skyline_text_v1
   skyline_theme_v1))
