(library
 (name skyline_date_input_v2)
 (public_name skyline.date_input_v2)
 (preprocess
  (pps ppx_jane js_of_ocaml-ppx bonsai.ppx_bonsai ppx_css ppx_html))
 (libraries bonsai_web bonsai_web_components.icon browser.expert core
   virtual_dom.css_gen js_of_ocaml bonsai_web_components.lucide
   private_skyline_prelude private_skyline_segmented_input skyline_field_v2
   skyline_tokens_v2 virtual_dom.keyboard))
