(library
 (name skyline_confirm_dialog_v2)
 (public_name skyline.confirm_dialog_v2)
 (preprocess
  (pps ppx_jane js_of_ocaml-ppx bonsai.ppx_bonsai ppx_css ppx_html))
 (libraries bonsai bonsai_web core virtual_dom.css_gen js_of_ocaml
   private_skyline_utility_classes skyline_button_v2 skyline_dialog_v2
   skyline_intent skyline_modal_v2 skyline_size)
 (flags :standard -alert -skyline_beta))
