(library
 (name skyline_switch_input_v2)
 (public_name skyline.switch_input_v2)
 (preprocess
  (pps ppx_jane js_of_ocaml-ppx bonsai.ppx_bonsai ppx_css ppx_html))
 (libraries bonsai bonsai_web bonsai_web_components.checkbox core
   virtual_dom.css_gen js_of_ocaml private_skyline_prelude
   private_skyline_utility_classes skyline_field_v2 skyline_intent
   skyline_size skyline_text_v2 skyline_tokens_v2)
 (flags :standard -alert -skyline_beta))
